site_name: Student Manager Documentation
site_url: https://www.studentmanager.co.za
repo_url: https://github.com/AgileSystemsTechnology/StudentManager.Docs
site_favicon: favicon.ico

pages:
- Home: index.md
   
- People:
    - Adding People: People/adding-people.md
    - System Access: People/systemaccess.md
    - Account Activation Link: People/sendanaccountactivationlink.md
    - Assign Roles : People/assignroles.md
    - Change Student Status: People/changestatusofstudent.md
    - De-enrolling a Student: People/de-enrollingastudent.md
    - Change a Student Number: People/changeastudentnumber.md
    - Change a Qualification: People/changeaqualification.md

- Modules:
    - Add a Module: Modules/addamodule.md
    - Linking Modules to Qualifications: Modules/linkingmodulestoqualifications.md
    - Copy Module Groups in Bulk: Modules/copymodulegroupsinbulk.md
    - Moving Modules: Modules/movingmodules.md
    - Setting up Module Groups: Modules/settingupmodulegroups.md
    - Setting up Assessments: Modules/settingupassessments.md
    - Assessment Attempts: Modules/assessmentattempts.md
    - Copy Assessments in Bulk: Modules/copyassessmentsinbulk.md
    - Online Tests: Modules/onlinetests.md
    - Online Assessment: Modules/onlineassessments.md
    - Assign Roles to Assessor or Lecturer: Modules/assignrolestoassessororlecturer.md
    - Grade Assessments: Modules/grading.md
    - Adding E-Learning Material: Modules/addinglearningmaterial.md 
    - Merging Duplicate Modules: Modules/mergingduplicatemodules.md
    - Setting Up Assessments: Modules/settingupassessments.md

- Qualifications:
    - Add a Qualification: Qualifications/addaqualification.md
    - Setup Curriculum: Qualifications/setupcurriculums.md
    - Changing Credits: Qualifications/changingcredits.md   
    - Enrolling a Student: Qualifications/enrollingastudent.md
    - Setup Qualification Intakes: Qualifications/campusqualificationintake.md
    - Create Intakes: Qualifications/creatingintakes.md 

- Reports:
    - Print a Lecture Time Table: Reports/printalecturetimetable.md
    - Print a Student Card: Reports/printingastudentcard.md
    - Printing Academic Transcripts: Reports/printingacademictranscripts.md

- Calendar:
    - Create Events: Calendar/createevents.md 

- Leads:
    - Setting up Workflow Steps and Rules : Leads/settingupworkflowstepsandrules.md
    - Convert Lead to Student: Leads/convertleadtostudent.md

- Applicants:
    - Adding an Applicant: Applications/addinganapplicant.md
        
- Communication:
    - Creating an Inbox: Communication/settingsupaninbox.md
    - Sending an SMS: Communication/sendingansms.md

- Moodle:
    - Moodle Integration: Moodle/moodleintegration.md

- More:
    - Creating and Moving Logs: More/creatingormovinglogs.md
    - Grade and Symbol Settings: More/gradeandsymbolsettings.md
    - Setting up Level Groupings: More/settinguplevelgroupings.md
    - Switch off Autogenerated Student Numbers: More/switchoffautostudentnumbers.md
    - Setting Student Fees: More/settingstudentfees.md
    - Send Bulk Activation Links: More/sendbulkactivationlinks.md
    - Request Details Update in Bulk: More/requestadetailsupdateinbulk.md
    - Student Fees: More/studentfees.md

- WhatsNew: /WhatsNew
    
theme: readthedocs